name: dl-keras-tf
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter=1.0*
  - jupyterlab=0.34*
  - matplotlib=3.0*
  - notebook=5.7*
  - pandas=0.23*
  - scikit-learn=0.20*
  - pip:
    - keras==2.2.3
    - tensorflow>=1.8
    - Pillow~=5.3
